# Site settings
baseurl = "https://jimmylin212.github.io"
languageCode = "zh-tw"
title = "Jimmy Lin"
theme = "cactus"
googleAnalytics = "UA-2756751-14"
disqusShortname = "jimmylin212-github-io"
staticDir = "static"
hasCJKLanguage = true
enableRobotsTXT = true
rssLimit = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[related]
	threshold = 80
	includeNewer = false
	toLower = false

	[[related.indices]]
		name  = "tags"
		weight = 100

[params]
	name = "Jimmy Lin"
	description = "Things that I learned"
	bio = "Programmer - Diver - Blogger"
	# Enter optionally your twitter account
	twitter = ""
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = "更多文章"
	readMoreCount = 3
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Programmer - Diver - Blogger"
	# tweet = ""
	# share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    facebook = "https://www.facebook.com/jimmylin212"
	linkedin = "https://www.linkedin.com/in/jimmylin212/"
    githubalt = "https://www.github.com/jimmylin212"
	stackoverflow = "https://stackoverflow.com/story/jimmylin212"
