version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.30.2
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: |
            git submodule sync && git submodule update --init
            HUGO_ENV=production hugo -v -d ~/project/public
      - run:
          name: "Test Website"
          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore
      - deploy:
          command: |
            cd ~/project/public
            git config --global user.email "jimmylin212@gmail.com"
            git config --global user.name "Jimmy Lin"
            git add -A
            git commit -m "Deploy from CircleCI"
            git push
