version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.30.2
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: |
            git submodule sync && git submodule update --init
            HUGO_ENV=production hugo -v
#      - run:
#          name: "Test Website"
#          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore --disable-external --checks-to-ignore "HtmlCheck"
      - add_ssh_keys:
          fingerprints:
            - "05:51:48:67:12:75:c9:c4:dc:b9:01:cd:85:56:96:ee"
      - deploy:
          name: "Deploy to github.io"       
          command: |
            cd ~/project/public
            git config --global user.email "jimmylin212@gmail.com"
            git config --global user.name "Jimmy Lin"
            git add -A
            git commit -m "Deploy from CircleCI"
            git push origin HEAD:master
