version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v
      - run:
          name: "Test Website"
          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore
      - deploy:
          command: |
            cd ~/project/public
            git add -A
            git commit -m "Deploy from CircleCI"
            git push
